// Generated by scripts/generate-content-manifest.mjs. Do not edit.
import { createContentManifest } from "meshova/pcg";
import contentModelTeddyBear from "./models/teddy-bear/index.js";
import contentMaterialRustyMetal from "./materials/rusty-metal/index.js";

export const contentManifest = createContentManifest([
  contentModelTeddyBear,
  contentMaterialRustyMetal,
]);
