/**
 * Procedural vegetation — a tree, a shrub, and a grass patch, all generated by
 * the P7 vegetation module (SpeedTree-style recursive spline branches + leaf
 * cards). Pure procedural, deterministic, zero art assets.
 *
 * Run: pnpm tsx examples/vegetation.ts
 */
import {
  tree,
  shrub,
  grass,
  conifer,
  palm,
  translateMesh,
  vec3,
  toViewerModel,
  type NamedPart,
} from "../src/index.js";

const BARK: [number, number, number] = [0.32, 0.22, 0.14];
const LEAF: [number, number, number] = [0.18, 0.42, 0.13];
const LEAF_LIGHT: [number, number, number] = [0.32, 0.55, 0.18];
const BLADE: [number, number, number] = [0.24, 0.5, 0.16];

interface Scene {
  id: string;
  name: string;
  parts: NamedPart[];
}

const scenes: Scene[] = [];

// --- Tree ---
{
  const t = tree({ seed: 7, height: 4.2, branchCount: 7, depth: 3, leafDensity: 9 });
  scenes.push({
    id: "veg-tree",
    name: "程序化树",
    parts: [
      { name: "trunk", mesh: t.wood, color: BARK },
      { name: "leaves", mesh: t.leaves, color: LEAF },
    ],
  });
}

// --- Shrub ---
{
  const s = shrub({ seed: 11, height: 1.5, stems: 6, leafDensity: 11 });
  scenes.push({
    id: "veg-shrub",
    name: "程序化灌木",
    parts: [
      { name: "stems", mesh: s.wood, color: BARK },
      { name: "foliage", mesh: s.leaves, color: LEAF_LIGHT },
    ],
  });
}

// --- Grass patch ---
{
  const g = grass({ seed: 5, blades: 320, area: 2.4, height: 0.45, bend: 0.22 });
  scenes.push({
    id: "veg-grass",
    name: "程序化草地",
    parts: [{ name: "blades", mesh: g.leaves, color: BLADE }],
  });
}

// --- Conifer (pine/spruce) ---
{
  const c = conifer({ seed: 3, height: 5.5, whorls: 10, perWhorl: 7, needleDensity: 5 });
  scenes.push({
    id: "veg-conifer",
    name: "程序化针叶树",
    parts: [
      { name: "trunk", mesh: c.wood, color: BARK },
      { name: "needles", mesh: c.leaves, color: [0.13, 0.34, 0.16] },
    ],
  });
}

// --- Palm ---
{
  const pl = palm({ seed: 4, height: 5, fronds: 10, frondLength: 1.9, lean: 0.45 });
  scenes.push({
    id: "veg-palm",
    name: "程序化棕榈树",
    parts: [
      { name: "trunk", mesh: pl.wood, color: [0.4, 0.3, 0.18] },
      { name: "fronds", mesh: pl.leaves, color: [0.22, 0.46, 0.16] },
    ],
  });
}

// --- Combined scene: tree + shrubs + grass arranged in a little plot ---
{
  const parts: NamedPart[] = [];
  const big = tree({ seed: 21, height: 4.5 });
  parts.push({ name: "tree_trunk", mesh: big.wood, color: BARK });
  parts.push({ name: "tree_leaves", mesh: big.leaves, color: LEAF });
  for (let i = 0; i < 3; i++) {
    const a = (i / 3) * Math.PI * 2;
    const sh = shrub({ seed: 30 + i, height: 1.2 });
    const off = vec3(Math.cos(a) * 2.6, 0, Math.sin(a) * 2.6);
    parts.push({ name: `shrub_${i}_wood`, mesh: translateMesh(sh.wood, off), color: BARK });
    parts.push({ name: `shrub_${i}_leaf`, mesh: translateMesh(sh.leaves, off), color: LEAF_LIGHT });
  }
  const ground = grass({ seed: 99, blades: 600, area: 7, height: 0.35 });
  parts.push({ name: "ground_grass", mesh: ground.leaves, color: BLADE });
  scenes.push({ id: "veg-garden", name: "植被花园", parts });
}

// --- Write viewer JSON + manifest ---
const fs = await import("node:fs");
const path = await import("node:path");
const outDir = path.resolve(process.cwd(), "out");
fs.mkdirSync(outDir, { recursive: true });

const manifestPath = path.join(outDir, "models.json");
let manifest: { models: Array<{ id: string; name: string; file: string }> } = { models: [] };
if (fs.existsSync(manifestPath)) {
  try {
    manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  } catch {
    /* rebuild on parse error */
  }
}

for (const scene of scenes) {
  const model = toViewerModel(scene.parts, scene.name);
  const file = `${scene.id}.json`;
  fs.writeFileSync(path.join(outDir, file), JSON.stringify(model));
  manifest.models = manifest.models.filter((m) => m.id !== scene.id);
  manifest.models.push({ id: scene.id, name: scene.name, file });
  console.log(`${scene.id}: ${model.meta.parts} parts, ${model.meta.verts} verts, ${model.meta.tris} tris`);
}

fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
console.log("written: out/veg-*.json + out/models.json");
