import { chromium } from "playwright";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
const shell=chromium.executablePath();
const full=shell.replace(/chromium_headless_shell-(\d+)/,"chromium-$1").replace(/chrome-headless-shell-win64[\/]chrome-headless-shell\.exe$/i,"chrome-win64\chrome.exe");
const browser=await chromium.launch({executablePath:existsSync(full)?full:undefined,headless:true,args:["--use-gl=angle","--ignore-gpu-blocklist","--headless=new"]});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errs=[];page.on("pageerror",e=>errs.push(String(e)));
page.on("console",message=>{if(message.type()==="error")errs.push(message.text())});
const input=process.argv[2]||"http://127.0.0.1:5199/web/tree-fit.html";
const url=/^https?:\/\//i.test(input)||/^file:/i.test(input)?input:pathToFileURL(resolve(input)).href;
const output=process.argv[3]||"out/tree-fit-page.png";
await page.goto(url,{waitUntil:"networkidle"});
await page.waitForTimeout(500);
await page.screenshot({path:output,fullPage:true});
const images=await page.$$eval("img",els=>({count:els.length,loaded:els.filter(el=>el.complete&&el.naturalWidth>0).length}));
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);
console.log("images:",`${images.loaded}/${images.count}`,"horizontal-overflow:",overflow,"errors:",errs.slice(0,3).join("|")||"none");
await browser.close();
