/**
 * Rooftop water tower — Meshova's take on the CitySample Kit_roof_tank props,
 * the wooden barrel-and-cone tanks that define the New York skyline. A staved
 * timber tank sits on a steel support frame, capped by a conical roof with a
 * finial; optional access ladder and hoop bands complete the silhouette.
 *
 * The staves are generated by wrapping N tapering boxes around a circle
 * (procedural, no baked mesh). Everything is parameter driven; the only
 * randomness is seeded per-stave weathering jitter, so same params -> same mesh
 * (Meshova determinism invariant). Base of the support legs sits at y=0.
 *
 * Run: pnpm tsx examples/water-tower.ts
 */
import { vec3 } from "../math/vec3.js";
import { makeRng } from "../random/prng.js";
import {
  box,
  cylinder,
  cone,
  torus,
  merge,
  transform,
  translateMesh,
  type Mesh,
  type NamedPart,
} from "../geometry/index.js";

type RGB = [number, number, number];

const WOOD_TANK: RGB = [0.42, 0.28, 0.16];
const WOOD_DARK: RGB = [0.3, 0.19, 0.1];
const METAL_HOOP: RGB = [0.2, 0.21, 0.23];
const STEEL: RGB = [0.4, 0.41, 0.44];

export interface WaterTowerParams {
  /** Tank barrel radius (metres). */
  radius: number;
  /** Tank barrel height (staved section). */
  tankHeight: number;
  /** Number of vertical staves around the barrel. */
  staves: number;
  /** Number of steel hoop bands around the tank. */
  hoops: number;
  /** Support-frame leg height under the tank. */
  legHeight: number;
  /** Conical roof pitch (roof height / radius). */
  roofPitch: number;
  /** Add an access ladder up one leg. */
  ladder: boolean;
  /** Seed for per-stave weathering jitter. */
  seed: number;
}

export const WATER_TOWER_DEFAULTS: WaterTowerParams = {
  radius: 1.6,
  tankHeight: 3.2,
  staves: 24,
  hoops: 4,
  legHeight: 2.4,
  roofPitch: 0.55,
  ladder: true,
  seed: 9,
};

const woodSurf = (color: RGB, roughness = 0.82) =>
  ({ type: "wood", params: { color, roughness } }) as const;
const metalSurf = (color: RGB, roughness = 0.5) =>
  ({ type: "metal", params: { color, roughness, metallic: 1 } }) as const;

/** Staved barrel: N tapering boxes wrapped around the tank circumference. */
function stavedTank(p: WaterTowerParams, baseY: number): Mesh {
  const rng = makeRng(p.seed >>> 0);
  const n = Math.max(8, Math.round(p.staves));
  const staveW = (2 * Math.PI * p.radius) / n * 1.05; // slight overlap
  const staveT = 0.1;
  const parts: Mesh[] = [];
  for (let i = 0; i < n; i++) {
    const a = (i / n) * Math.PI * 2;
    const wob = rng.range(-0.02, 0.02); // weathering: tiny radial/height wobble
    const h = p.tankHeight + rng.range(-0.03, 0.06);
    const stave = box(staveW, h, staveT);
    const r = p.radius + wob;
    const placed = transform(stave, {
      rotate: vec3(0, -a, 0),
      translate: vec3(Math.cos(a) * r, baseY + h / 2, Math.sin(a) * r),
    });
    parts.push(placed);
  }
  // Flat tank floor just inside the staves.
  parts.push(translateMesh(cylinder(p.radius * 0.98, 0.12, n), vec3(0, baseY + 0.06, 0)));
  return merge(...parts);
}

/** Steel hoop bands (torus rings) girding the tank at even heights. */
function hoops(p: WaterTowerParams, baseY: number): Mesh {
  const parts: Mesh[] = [];
  const n = Math.max(2, Math.round(p.hoops));
  for (let i = 0; i < n; i++) {
    const y = baseY + p.tankHeight * ((i + 0.5) / n);
    parts.push(transform(torus(p.radius + 0.06, 0.035, 8, Math.max(20, Math.round(p.staves))), {
      rotate: vec3(Math.PI / 2, 0, 0),
      translate: vec3(0, y, 0),
    }));
  }
  return merge(...parts);
}

/** Conical roof with a finial ball, capping the tank. */
function roof(p: WaterTowerParams, topY: number): Mesh {
  const roofH = p.radius * p.roofPitch;
  const cap = translateMesh(cone(p.radius * 1.08, roofH, Math.max(16, Math.round(p.staves))), vec3(0, topY + roofH / 2, 0));
  const finialPost = translateMesh(cylinder(0.05, 0.4, 8), vec3(0, topY + roofH + 0.2, 0));
  const finialBall = translateMesh(cone(0.12, 0.2, 10), vec3(0, topY + roofH + 0.48, 0));
  return merge(cap, finialPost, finialBall);
}

/** Four steel A-legs + cross bracing carrying the tank. */
function support(p: WaterTowerParams): Mesh {
  const parts: Mesh[] = [];
  const legR = p.radius * 0.92;
  const legAngles = [Math.PI / 4, (3 * Math.PI) / 4, (5 * Math.PI) / 4, (7 * Math.PI) / 4];
  const feet: Vec3Tuple[] = [];
  for (const a of legAngles) {
    const fx = Math.cos(a) * legR;
    const fz = Math.sin(a) * legR;
    feet.push([fx, fz]);
    // Leg leans slightly inward toward the tank base.
    const topX = Math.cos(a) * (p.radius * 0.6);
    const topZ = Math.sin(a) * (p.radius * 0.6);
    const dx = topX - fx;
    const dz = topZ - fz;
    const len = Math.hypot(dx, dz, p.legHeight);
    const leg = box(0.14, len, 0.14);
    // Orient leg from foot to top.
    const midX = (fx + topX) / 2;
    const midZ = (fz + topZ) / 2;
    const tiltX = Math.atan2(dz, p.legHeight);
    const tiltZ = -Math.atan2(dx, p.legHeight);
    parts.push(transform(leg, { rotate: vec3(tiltX, 0, tiltZ), translate: vec3(midX, p.legHeight / 2, midZ) }));
  }
  // Horizontal ring bracing at two heights.
  for (const hy of [p.legHeight * 0.35, p.legHeight * 0.75]) {
    parts.push(transform(torus(legR * 0.95, 0.03, 6, 24), { rotate: vec3(Math.PI / 2, 0, 0), translate: vec3(0, hy, 0) }));
  }
  return merge(...parts);
}

type Vec3Tuple = [number, number];

/** Vertical access ladder up the +X leg. */
function ladder(p: WaterTowerParams): Mesh {
  const parts: Mesh[] = [];
  const x = p.radius * 0.95;
  const topY = p.legHeight + p.tankHeight;
  for (const rx of [x - 0.16, x + 0.16]) {
    parts.push(translateMesh(box(0.03, topY, 0.03), vec3(rx, topY / 2, 0)));
  }
  const rungs = Math.max(4, Math.round(topY / 0.35));
  for (let i = 0; i < rungs; i++) {
    const y = 0.2 + i * (topY - 0.3) / rungs;
    parts.push(transform(cylinder(0.02, 0.32, 6), { rotate: vec3(0, 0, Math.PI / 2), translate: vec3(x, y, 0) }));
  }
  return merge(...parts);
}

export function buildWaterTowerParts(params: Partial<WaterTowerParams> = {}): NamedPart[] {
  const p: WaterTowerParams = { ...WATER_TOWER_DEFAULTS, ...params };
  const baseY = p.legHeight;
  const topY = baseY + p.tankHeight;

  const parts: NamedPart[] = [
    { name: "support", label: "支撑架", mesh: support(p), color: STEEL, surface: metalSurf(STEEL, 0.55) },
    { name: "tank", label: "木桶罐体", mesh: stavedTank(p, baseY), color: WOOD_TANK, surface: woodSurf(WOOD_TANK, 0.85) },
    { name: "hoops", label: "钢箍", mesh: hoops(p, baseY), color: METAL_HOOP, surface: metalSurf(METAL_HOOP, 0.45) },
    { name: "roof", label: "锥顶", mesh: roof(p, topY), color: WOOD_DARK, surface: woodSurf(WOOD_DARK, 0.8) },
  ];
  if (p.ladder) {
    parts.push({ name: "ladder", label: "爬梯", mesh: ladder(p), color: METAL_HOOP, surface: metalSurf(METAL_HOOP, 0.5) });
  }
  return parts.map((part) => ({ ...part, metadata: { source: "CitySample Kit_roof_tank" } }));
}
